---
title: "Mortality in Sweden"
author: Tommi Suvitaival, tommi.raimo.leo.suvitaival@regionh.dk, Steno Diabetes Center
  Copenhagen
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 600,
  fig.width = 6,
  fig.height = 6
)

```

## Load Data

* Data from Statistics Sweden SCB:
  + Överdödligheten sjunker i Sverige
  + https://www.scb.se/om-scb/nyheter-och-pressmeddelanden/overdodligheten-sjunker-i-sverige/
  + Preliminär statistik över döda (excelfil)
  + https://www.scb.se/hitta-statistik/statistik-efter-amne/befolkning/befolkningens-sammansattning/befolkningsstatistik/pong/tabell-och-diagram/preliminar-statistik-over-doda/

```{r Load}

data.loaded <-
  readxl::read_excel(
    path = "H:/projects/covid19/data/SCB/2020-05-08---preliminar-statistik-over-doda-inkl-eng.xlsx",
    sheet = "Tabell 7",
    skip = 8
  )

```

## Prepare Data

### Add Unassigned Deaths to Total

```{r Unassigned}

data <- data.loaded

data[ data == 0 ] <- NA

tmp <- which( data$"Vecka" == "Uppgift saknas" ) 

idx.data <- 2:19

data.before.adding <- data

for ( i in 1:length( idx.data ) ) {
  
  idx.obs.i <- which( !is.na( data[ -tmp, idx.data[ i ] ] ) )
  
  data[ idx.obs.i, idx.data[ i ] ] <- 
    data[ idx.obs.i, idx.data[ i ] ] +
    unlist( data[ tmp, idx.data[ i ] ] ) / length( idx.obs.i )
  
}

```


### Bind Periods

```{r Long}

tmp <- data.loaded

colnames( tmp ) <-
  stringr::str_replace(
    string = colnames( tmp ),
    pattern = "\\.\\.\\.[0-9]+$",
    replacement = ""
  )

data <- tmp[ , 1:10 ]

data$"Period" <- colnames( data )[ 2 ]

colnames( data )[ 2 ] <- "Total"

tmp <- tmp[ , c( 1, 11:19 ) ]

tmp$"Period" <- colnames( tmp )[ 2 ]

colnames( tmp )[ 2 ] <- "Total"

tmp[ tmp == 0 ] <- NA

data <-
  dplyr::bind_rows(
    data,
    tmp
  )

tmp <- data

data <- data[ , -c( 2, 7:10 ) ]

colnames( data ) <-
  stringr::str_replace(
    string = colnames( data ),
    pattern = "^M ",
    replacement = ""
  )

tmp <- tmp[ , -( 2:6 ) ]

colnames( tmp ) <-
  stringr::str_replace(
    string = colnames( tmp ),
    pattern = "^K ",
    replacement = ""
  )

data <-
  dplyr::bind_rows(
    Male = data,
    Female = tmp,
    .id = "Sex"
  )

data$"Period" <-
  relevel(
    x = as.factor( data$"Period" ),
    ref = "2020"
  )

```

### Translate

```{r Translate}

colnames( data )[ colnames( data ) == "Vecka" ] <- "Week"

colnames( data ) <-
  stringr::str_replace(
    string = colnames( data ),
    pattern = "år",
    replacement = "years"
  )

```

### Pivot to Longer Format

```{r Pivot-Longer}

data.plot <- data

data.plot$"Week" <- as.numeric( data.plot$"Week" )

data.plot <- data.plot[ !is.na( data.plot$"Week" ), ]

data.plot <-
  tidyr::pivot_longer(
    data = data.plot,
    cols =
      colnames( data.plot )[
        grep(
          x = colnames( data.plot ),
          pattern = "(Total)|(years)"
        )
        ],
    names_to = "Age",
    values_to = "Deaths"
  )

```

### Omit Incomplete Weeks

```{r Omit-Incomplete}

data.plot <-
  dplyr::filter(
    .data = data.plot,
    Week != 1 &
      Week < 51
  )

tmp <- 
  data.plot$"Period" == levels( data.plot$"Period" )[ 1 ] &
  !is.na( data.plot$"Deaths" )

tmp <- data.plot[ tmp, "Week" ]

tmp <- max( unlist( tmp ) )

data.plot <-
  dplyr::filter(
    .data = data.plot,
    # Week < tmp - 1 |
    Week < tmp |
      Period != levels( data.plot$"Period" )[ 1 ]
  )

```

## Plot

### By Sex

```{r Plot-Sex}

ggplot2::ggplot(
  data = data.plot,
  mapping =
    ggplot2::aes(
      x = Week,
      y = Deaths,
      color = Age,
      linetype = Period,
      shape = Period
    )
) +
  ggplot2::geom_point( alpha = 0.75 ) +
  ggplot2::geom_smooth() +
  ggplot2::scale_y_log10() +
  ggplot2::facet_grid(
    col = ggplot2::vars( Sex )
  ) +
  ggplot2::scale_color_brewer(
    palette = "Set1",
    direction = -1
  ) +
  ggplot2::theme(
    legend.position = "top",
    legend.direction = "vertical"
  )

```

### By Age Groups

```{r Plot-Age}

ggplot2::ggplot(
  data = data.plot,
  mapping =
    ggplot2::aes(
      x = Week,
      y = Deaths,
      color = Period,
      linetype = Sex,
      shape = Sex
    )
) +
  ggplot2::geom_point( alpha = 0.75 ) +
  ggplot2::geom_smooth() +
  ggplot2::scale_y_log10() +
  ggplot2::facet_wrap(
    facets = ggplot2::vars( Age )
  ) +
  ggplot2::scale_color_brewer(
    palette = "Set1"
    # ,
    # direction = -1
  )

```

### By Age Groups and Sex

```{r Plot-Age-and-Sex}

ggplot2::ggplot(
  data = data.plot,
  mapping =
    ggplot2::aes(
      x = Week,
      y = Deaths,
      color = Period,
      linetype = Period,
      shape = Period
    )
) +
  ggplot2::geom_point( alpha = 0.75 ) +
  ggplot2::geom_smooth() +
  ggplot2::scale_y_log10() +
  ggplot2::facet_grid(
    cols = ggplot2::vars( Sex ),
    rows = ggplot2::vars( Age ),
    scales = "free_y"
  ) +
  ggplot2::scale_color_brewer(
    palette = "Set1"
    # ,
    # direction = -1
  )

```

```{r Plot-Age-and-Sex-B, fig.width = 7}

ggplot2::ggplot(
  data = data.plot,
  mapping =
    ggplot2::aes(
      x = Week,
      y = Deaths,
      color = Period,
      linetype = Period,
      shape = Period
    )
) +
  ggplot2::geom_point( alpha = 0.75 ) +
  ggplot2::geom_smooth() +
  ggplot2::scale_y_log10() +
  ggplot2::facet_grid(
    rows = ggplot2::vars( Sex ),
    cols = ggplot2::vars( Age )
  ) +
  ggplot2::scale_color_brewer(
    palette = "Set1"
  ) +
  ggplot2::theme(
    legend.position = "top"
  )

```

## Appendix

```{r SessionInfo}

utils::sessionInfo()

```